services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DBType=sqlite
      - DBURL=/app/data/app.db
    volumes:
      - ./backend:/app
      - sqlite_storage:/app/data

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

volumes:
  sqlite_storage:
  caddy_data:
  caddy_config: