services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - DBType=sqlite
      - DBURL=/app/data/app.db
    volumes:
      - ./backend:/app
      - sqlite_storage:/app/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  sqlite_storage: